### ISSUE TITLE
Are you planning to support Machine Learning framework?

### ISSUE THREAD

**Issue by solderzzc** [CMU-SAFARI/prim-benchmarks#8]
Thanks for bring DPU to industry, I'm wondering if there's roadmap for supporting machine learning framework in the future? 
So we can use DPU as machine learning inference engine in datacenter scenario.

**Comment by el1goluj** [comment]
That is a promising direction. A recommended reading about some preliminary work: https://arxiv.org/pdf/2206.06022.pdf
